package schema

import (
	"context"
	"database/sql"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/stripe/pg-schema-diff/pkg/diff"
	"github.com/stripe/pg-schema-diff/pkg/tempdb"
)

// DiffResult holds the output of diffing a schema file against the live database.
type DiffResult struct {
	Name       string          // from S__{name}.sql
	Statements []DiffStatement // ordered ALTER statements to reach desired state
	HasChanges bool
}

// DiffStatement represents a single DDL statement generated by the schema differ.
type DiffStatement struct {
	DDL         string        // The SQL statement to execute.
	Hazards     []string      // Safety warnings (e.g., "ACQUIRES_ACCESS_EXCLUSIVE_LOCK").
	Timeout     time.Duration // Suggested statement_timeout.
	LockTimeout time.Duration // Suggested lock_timeout.
}

// Differ computes the difference between a desired-state DDL definition
// and the live database schema, producing ALTER statements to converge.
type Differ struct {
	connStr     string         // connection string for creating temp databases
	tempFactory tempdb.Factory // creates temp DBs for DDL parsing
}

// NewDiffer creates a Differ that uses the given connection string for
// both introspecting the live database and creating temp databases for
// DDL parsing.
func NewDiffer(ctx context.Context, connStr string) (*Differ, error) {
	factory, err := tempdb.NewOnInstanceFactory(ctx, func(ctx context.Context, dbName string) (*sql.DB, error) {
		tempConnStr := replaceDBName(connStr, dbName)
		db, err := sql.Open("pgx", tempConnStr)
		if err != nil {
			return nil, err
		}
		// Disable statement_timeout so CREATE/DROP DATABASE don't get killed
		// on connections with role-level timeouts configured.
		_, _ = db.ExecContext(ctx, "SET statement_timeout = 0")
		return db, nil
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create temp database factory: %w", err)
	}

	return &Differ{
		connStr:     connStr,
		tempFactory: factory,
	}, nil
}

// Close cleans up the temp database factory.
func (d *Differ) Close() error {
	return d.tempFactory.Close()
}

// Diff compares the desired DDL (from an S__ file) against the live database
// for a given schema and returns the ALTER statements needed to converge.
//
// When strict is false (default), only statements targeting objects defined in
// the DDL are included — undeclared objects in the live DB are ignored.
// When strict is true, all diff statements are included, including DROPs for
// objects that exist in the DB but not in the DDL.
func (d *Differ) Diff(ctx context.Context, liveDB *sql.DB, targetSchema string, desiredDDL []string, strict bool) (*DiffResult, error) {
	plan, err := diff.Generate(ctx,
		diff.DBSchemaSource(liveDB),
		diff.DDLSchemaSource(desiredDDL),
		diff.WithTempDbFactory(d.tempFactory),
	)
	if err != nil {
		return nil, fmt.Errorf("failed to generate schema diff: %w", err)
	}

	// In default (non-strict) mode, only include statements targeting objects
	// defined in the DDL. In strict mode, include everything except _m8 internals.
	var definedObjects map[string]bool
	if !strict {
		definedObjects = extractDefinedObjects(desiredDDL)
	}

	result := &DiffResult{}

	for _, stmt := range plan.Statements {
		// Always exclude m8 internal schema
		lower := strings.ToLower(stmt.DDL)
		if strings.Contains(lower, `"_m8"`) || strings.Contains(lower, `_m8.`) {
			continue
		}

		if !strict {
			if !statementTargetsDefinedObject(stmt.DDL, definedObjects) {
				continue
			}
		}
		ds := DiffStatement{
			DDL:         stmt.DDL,
			Timeout:     stmt.Timeout,
			LockTimeout: stmt.LockTimeout,
		}
		for _, h := range stmt.Hazards {
			ds.Hazards = append(ds.Hazards, string(h.Type))
		}
		result.Statements = append(result.Statements, ds)
	}

	result.HasChanges = len(result.Statements) > 0
	return result, nil
}

var (
	// Matches: CREATE TABLE [IF NOT EXISTS] [schema.]tablename
	createTableRe = regexp.MustCompile(`(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:"?\w+"?\.)?("?\w+"?)`)
	// Matches: CREATE [UNIQUE] INDEX [CONCURRENTLY] [IF NOT EXISTS] indexname
	createIndexRe = regexp.MustCompile(`(?i)CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?("?\w+"?)`)
)

// extractDefinedObjects parses the desired DDL statements and returns the set
// of object names (tables, indexes) that are explicitly defined. Names are
// stored unquoted and lowercased for case-insensitive matching.
func extractDefinedObjects(ddlStatements []string) map[string]bool {
	objects := make(map[string]bool)
	combined := strings.Join(ddlStatements, "\n")

	for _, m := range createTableRe.FindAllStringSubmatch(combined, -1) {
		name := strings.Trim(m[1], `"`)
		objects[strings.ToLower(name)] = true
	}
	for _, m := range createIndexRe.FindAllStringSubmatch(combined, -1) {
		name := strings.Trim(m[1], `"`)
		objects[strings.ToLower(name)] = true
	}
	return objects
}

// statementTargetsDefinedObject returns true if the DDL statement modifies an
// object that was defined in the S__ file. This prevents pg-schema-diff from
// generating DROP/ALTER/REVOKE statements for unrelated objects that exist in
// the live database but aren't mentioned in the desired DDL.
func statementTargetsDefinedObject(ddl string, defined map[string]bool) bool {
	lower := strings.ToLower(ddl)

	// Always exclude m8 internal schema
	if strings.Contains(lower, `"_m8"`) || strings.Contains(lower, `_m8.`) {
		return false
	}

	// Exclude GRANT/REVOKE — privileges are managed by R__ migrations, not S__
	if strings.HasPrefix(lower, "grant ") || strings.HasPrefix(lower, "revoke ") {
		return false
	}

	// Check if any defined object name appears in the statement.
	// pg-schema-diff quotes table names ("users") but not index names (idx_foo).
	for name := range defined {
		if strings.Contains(lower, `"`+name+`"`) {
			return true
		}
		if containsWord(lower, name) {
			return true
		}
	}
	return false
}

// containsWord checks if s contains word as a whole word (not a substring of
// a longer identifier). Uses simple boundary checking on adjacent characters.
func containsWord(s, word string) bool {
	for i := 0; i <= len(s)-len(word); i++ {
		if s[i:i+len(word)] != word {
			continue
		}
		// Check character before
		if i > 0 && isIdentChar(s[i-1]) {
			continue
		}
		// Check character after
		end := i + len(word)
		if end < len(s) && isIdentChar(s[end]) {
			continue
		}
		return true
	}
	return false
}

func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
		(c >= '0' && c <= '9') || c == '_'
}

// replaceDBName replaces the database name in a PostgreSQL connection string.
// Handles both URL format (postgres://.../<dbname>) and key=value format (dbname=...).
func replaceDBName(connStr, newDB string) string {
	// URL format: postgres://user:pass@host:port/dbname?params
	if strings.HasPrefix(connStr, "postgres://") || strings.HasPrefix(connStr, "postgresql://") {
		// Find the path component (database name)
		parts := strings.SplitN(connStr, "?", 2)
		base := parts[0]

		// Find the last / which precedes the dbname
		lastSlash := strings.LastIndex(base, "/")
		if lastSlash == -1 {
			return connStr
		}

		newBase := base[:lastSlash+1] + newDB
		if len(parts) > 1 {
			return newBase + "?" + parts[1]
		}
		return newBase
	}

	// Key=value format: host=... port=... dbname=... user=...
	parts := strings.Fields(connStr)
	var result []string
	found := false
	for _, part := range parts {
		if strings.HasPrefix(part, "dbname=") {
			result = append(result, "dbname="+newDB)
			found = true
		} else {
			result = append(result, part)
		}
	}
	if !found {
		result = append(result, "dbname="+newDB)
	}
	return strings.Join(result, " ")
}
