package schema

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/ags-slc/m8/internal/pgident"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/stripe/pg-schema-diff/pkg/diff"
	"github.com/stripe/pg-schema-diff/pkg/tempdb"
)

// DiffResult holds the output of diffing a schema file against the live database.
type DiffResult struct {
	Name       string          // from S__{name}.sql
	Statements []DiffStatement // ordered ALTER statements to reach desired state
	HasChanges bool
	// ValidationSkipped is set when the plan could not be validated against a
	// throwaway rebuild of the current schema. The diff itself is unaffected;
	// only the extra check that the generated statements execute is missing.
	// ValidationSkippedReason carries the underlying error for the operator.
	ValidationSkipped       bool
	ValidationSkippedReason string
	// SeededSchemas names the schemas m8 had to import into the throwaway
	// rebuild before the plan could be validated. Empty on the common path.
	// A validated plan that needed an import should say so: it was checked
	// against a copy of another schema, not against that schema itself.
	SeededSchemas []string
	// RecoveryNote explains what m8 did, or could not do, to make validation
	// possible. Carried separately rather than appended to
	// ValidationSkippedReason: that string is a multi-line pg-schema-diff error
	// and every caller renders only its first line, so anything appended to it
	// is invisible exactly when it matters.
	RecoveryNote string
}

// DiffStatement represents a single DDL statement generated by the schema differ.
type DiffStatement struct {
	DDL         string        // The SQL statement to execute.
	Hazards     []string      // Safety warnings (e.g., "ACQUIRES_ACCESS_EXCLUSIVE_LOCK").
	Timeout     time.Duration // Suggested statement_timeout.
	LockTimeout time.Duration // Suggested lock_timeout.
}

// tempDropTimeout caps how long pg-schema-diff's cleanup may spend dropping a
// temporary shadow database. The library defaults to 3s (tempdb.DefaultStatementTimeout),
// which is far too aggressive on a loaded instance: a DROP DATABASE that exceeds it
// is interrupted, leaving the database INVALID (pg_database.datconnlimit = -2) and
// orphaned. A generous ceiling lets the drop complete. See SweepInvalidTempDBs for
// remediation of any that still slip through.
const tempDropTimeout = 5 * time.Minute

// StaleTempDBTTL is the age past which a *valid* orphaned temp database is
// considered abandoned and eligible for cleanup. A schema diff uses its temp
// database for only seconds, so an hour is far longer than any in-flight run
// could legitimately hold one — making TTL-based cleanup safe even on a shadow
// instance shared by several targets.
const StaleTempDBTTL = time.Hour

// tempDBPrefix is the prefix pg-schema-diff gives every temp database it
// creates. The LIKE patterns in the sweeps below must match it.
const tempDBPrefix = tempdb.DefaultOnInstanceDbPrefix

// tempDBTracker records the temp databases the factory was asked to create on
// behalf of this process, so teardown can reclaim any whose drop never ran.
type tempDBTracker struct {
	mu    sync.Mutex
	names map[string]struct{}
}

func (t *tempDBTracker) add(name string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.names[name] = struct{}{}
}

func (t *tempDBTracker) list() []string {
	t.mu.Lock()
	defer t.mu.Unlock()
	out := make([]string, 0, len(t.names))
	for n := range t.names {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// Differ computes the difference between a desired-state DDL definition
// and the live database schema, producing ALTER statements to converge.
type Differ struct {
	connStr       string         // connection string for the live target database
	shadowConnStr string         // connection string for the instance hosting temp DBs
	tempFactory   tempdb.Factory // creates temp DBs for DDL parsing/plan validation
	// seedDDL is applied to every temp database the factory creates while it is
	// non-nil. Guarded because pg-schema-diff may create temp databases from
	// more than one goroutine, and the arm/disarm is done by the Diff that owns
	// the validation retry.
	seedMu      sync.Mutex
	seedDDL     []string
	seedSkipped []string
	created     *tempDBTracker // temp DBs this process asked the factory to create
}

// NewDiffer creates a Differ. The live target database (introspected for the
// current schema) is reached via targetConnStr. Temporary shadow databases —
// which pg-schema-diff creates and drops to parse desired DDL and validate plans
// (named pgschemadiff_tmp_*) — are created on the instance reached via
// shadowConnStr.
//
// IMPORTANT: when shadowConnStr is empty, temp databases are created on the
// TARGET instance itself. Against a production primary this churns
// CREATE/DROP DATABASE on the live cluster — pass a separate, non-production
// shadow instance to avoid that.
func NewDiffer(ctx context.Context, targetConnStr, shadowConnStr string) (*Differ, error) {
	if shadowConnStr == "" {
		shadowConnStr = targetConnStr
	}

	// pg-schema-diff's factory defaults its root connection to a database named
	// "postgres" and asserts at construction that it landed there, which would make
	// a reachable "postgres" database a hidden requirement of every shadow instance
	// — one some managed providers don't satisfy. Pin the root database to the one
	// the shadow connection string already names, so the factory and our own
	// cleanup connection (see rootConn) agree, and the only database an operator
	// must provide is the one they configured.
	rootDB, err := databaseName(shadowConnStr)
	if err != nil {
		return nil, fmt.Errorf("resolving shadow database name: %w", err)
	}

	created := &tempDBTracker{names: make(map[string]struct{})}
	// The factory callback needs the Differ to read its armed seed, and the
	// Differ needs the factory. Declared here, assigned below, and never read
	// before NewDiffer returns -- the factory does not invoke the callback
	// during construction.
	differ := &Differ{}

	factory, err := tempdb.NewOnInstanceFactory(ctx, func(ctx context.Context, dbName string) (*sql.DB, error) {
		// The factory calls this for its root connection too; only temp databases
		// are ours to reclaim.
		if strings.HasPrefix(dbName, tempDBPrefix) {
			created.add(dbName)
		}
		// Replace the database name first, THEN append statement_timeout=0.
		// replaceDBName tokenizes key=value DSNs on whitespace and would corrupt
		// a quoted options='...' value, so options must be appended last.
		// statement_timeout=0 must live in the connection string itself because
		// sql.Open is lazy and a SET may not reach the factory's connections.
		tempConnStr := appendConnOption(replaceDBName(shadowConnStr, dbName), "statement_timeout", "0")
		db, err := sql.Open("pgx", tempConnStr)
		if err != nil {
			return nil, err
		}
		// Only real temp databases, and only while a validation retry has armed
		// the seed. The factory's own root connection must never be touched.
		if strings.HasPrefix(dbName, tempDBPrefix) {
			differ.noteSkipped(differ.applySeed(ctx, db))
		}
		return db, nil
	}, tempdb.WithDropTimeout(tempDropTimeout), tempdb.WithRootDatabase(rootDB))
	if err != nil {
		return nil, fmt.Errorf("failed to create temp database factory: %w", err)
	}

	differ.connStr = targetConnStr
	differ.shadowConnStr = shadowConnStr
	differ.tempFactory = factory
	differ.created = created
	return differ, nil
}

// CreatedTempDBs returns the names of the temp databases this Differ asked the
// factory to create, in sorted order, whether or not they still exist.
func (d *Differ) CreatedTempDBs() []string {
	return d.created.list()
}

// DropCreatedTempDBs drops any temp database this Differ created that still
// exists, and returns how many it dropped.
//
// pg-schema-diff issues its drops on the caller's context. When that context is
// cancelled, database/sql refuses to hand out a connection at all, so the drop is
// never even sent and the temp database survives as a perfectly *valid* orphan —
// invisible to SweepInvalidTempDBs, and untouched by the TTL sweep for an hour.
// Dropping strictly by the names this process created is safe alongside other m8
// runs sharing one shadow instance: it can never reach a database another process
// owns, which is what makes it safe to run without any age or liveness heuristic.
func (d *Differ) DropCreatedTempDBs(ctx context.Context) (int, error) {
	names := d.created.list()
	if len(names) == 0 {
		return 0, nil
	}

	db, conn, err := d.rootConn(ctx)
	if err != nil {
		return 0, err
	}
	defer func() { _ = db.Close() }()
	defer func() { _ = conn.Close() }()

	existing := make(map[string]bool, len(names))
	rows, err := conn.QueryContext(ctx,
		`SELECT datname FROM pg_database WHERE datname LIKE 'pgschemadiff\_tmp\_%'`)
	if err != nil {
		return 0, fmt.Errorf("listing temp databases: %w", err)
	}
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			_ = rows.Close()
			return 0, fmt.Errorf("scanning temp database name: %w", err)
		}
		existing[n] = true
	}
	_ = rows.Close()
	if err := rows.Err(); err != nil {
		return 0, fmt.Errorf("iterating temp databases: %w", err)
	}

	dropped := 0
	for _, n := range names {
		if !existing[n] {
			continue
		}
		stmt := fmt.Sprintf("DROP DATABASE IF EXISTS %s WITH (FORCE)", pgident.Quote(n))
		if _, err := conn.ExecContext(ctx, stmt); err != nil {
			return dropped, fmt.Errorf("dropping temp database %s left by this run: %w", n, err)
		}
		dropped++
	}
	return dropped, nil
}

// SweepInvalidTempDBs drops any orphaned pgschemadiff_tmp_* databases on the
// shadow instance that Postgres has marked INVALID (datconnlimit = -2) — the
// residue of a DROP DATABASE that was interrupted (e.g. by a statement timeout).
// Invalid databases cannot be connected to, so dropping them is always safe even
// when another m8 process is running. It returns the number of databases dropped.
func (d *Differ) SweepInvalidTempDBs(ctx context.Context) (int, error) {
	db, conn, err := d.rootConn(ctx)
	if err != nil {
		return 0, err
	}
	defer func() { _ = db.Close() }()
	defer func() { _ = conn.Close() }()

	rows, err := conn.QueryContext(ctx,
		`SELECT datname FROM pg_database WHERE datname LIKE 'pgschemadiff\_tmp\_%' AND datconnlimit = -2`)
	if err != nil {
		return 0, fmt.Errorf("listing invalid temp databases: %w", err)
	}
	var names []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			_ = rows.Close()
			return 0, fmt.Errorf("scanning temp database name: %w", err)
		}
		names = append(names, n)
	}
	_ = rows.Close()
	if err := rows.Err(); err != nil {
		return 0, fmt.Errorf("iterating temp databases: %w", err)
	}

	dropped := 0
	for _, n := range names {
		stmt := fmt.Sprintf("DROP DATABASE IF EXISTS %s WITH (FORCE)", pgident.Quote(n))
		if _, err := conn.ExecContext(ctx, stmt); err != nil {
			return dropped, fmt.Errorf("dropping orphaned temp database %s: %w", n, err)
		}
		dropped++
	}
	return dropped, nil
}

// SweepStaleTempDBs drops valid (non-invalid) orphaned pgschemadiff_tmp_*
// databases on the shadow instance that have no active connections and whose
// recorded creation time (written by pg-schema-diff into its metadata table) is
// older than maxAge. This reclaims temp databases leaked by a process that died
// before its drop ran — the case SweepInvalidTempDBs (which only handles
// already-invalid databases) cannot cover.
//
// It is intentionally conservative: a database is dropped only when its age can
// be confirmed from metadata. Databases missing the metadata, busy, or otherwise
// uninspectable are left untouched. Callers should run this only against a
// dedicated shadow instance, never the live target. Returns the number dropped.
func (d *Differ) SweepStaleTempDBs(ctx context.Context, maxAge time.Duration) (int, error) {
	db, conn, err := d.rootConn(ctx)
	if err != nil {
		return 0, err
	}
	defer func() { _ = db.Close() }()
	defer func() { _ = conn.Close() }()

	// Candidates: valid temp databases with no active backends.
	rows, err := conn.QueryContext(ctx, `
		SELECT d.datname
		FROM pg_database d
		LEFT JOIN pg_stat_database s ON s.datname = d.datname
		WHERE d.datname LIKE 'pgschemadiff\_tmp\_%'
		  AND d.datconnlimit <> -2
		  AND d.datname <> current_database()
		  AND COALESCE(s.numbackends, 0) = 0`)
	if err != nil {
		return 0, fmt.Errorf("listing stale temp databases: %w", err)
	}
	var names []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			_ = rows.Close()
			return 0, fmt.Errorf("scanning temp database name: %w", err)
		}
		names = append(names, n)
	}
	_ = rows.Close()
	if err := rows.Err(); err != nil {
		return 0, fmt.Errorf("iterating temp databases: %w", err)
	}

	dropped := 0
	for _, n := range names {
		// Only drop when we can positively confirm the database is stale.
		if old, err := d.tempDBOlderThan(ctx, n, maxAge); err != nil || !old {
			continue
		}
		stmt := fmt.Sprintf("DROP DATABASE IF EXISTS %s WITH (FORCE)", pgident.Quote(n))
		if _, err := conn.ExecContext(ctx, stmt); err != nil {
			return dropped, fmt.Errorf("dropping stale temp database %s: %w", n, err)
		}
		dropped++
	}
	return dropped, nil
}

// tempDBOlderThan reports whether the temp database's recorded creation time is
// older than maxAge, by reading pg-schema-diff's metadata table inside it. Any
// error (missing metadata table, empty table, unreachable) is returned so the
// caller can leave the database alone rather than drop something it can't vet.
func (d *Differ) tempDBOlderThan(ctx context.Context, dbName string, maxAge time.Duration) (bool, error) {
	connStr := appendConnOption(replaceDBName(d.shadowConnStr, dbName), "statement_timeout", "0")
	db, err := sql.Open("pgx", connStr)
	if err != nil {
		return false, err
	}
	defer func() { _ = db.Close() }()

	var old bool
	err = db.QueryRowContext(ctx,
		`SELECT max(db_created_at) < now() - $1::interval FROM pgschemadiff_tmp_metadata.metadata`,
		fmt.Sprintf("%d seconds", int64(maxAge.Seconds()))).Scan(&old)
	if err != nil {
		return false, err
	}
	return old, nil
}

// rootConn opens a single pinned connection to the shadow instance with
// statement_timeout disabled, used for the catalog queries and DROP DATABASE
// statements the sweeps issue.
//
// It connects to the database named in the shadow connection string, which is
// also what NewDiffer pins pg-schema-diff's own root connection to — so cleanup
// and temp database creation always operate from the same place, and neither
// requires a "postgres" database to exist. DROP DATABASE works from any database
// in the cluster except the one being dropped, which the stale sweep excludes
// explicitly.
//
// Pinning one connection (rather than using the *sql.DB pool directly)
// guarantees the statement_timeout reset and the subsequent statements all run
// on the same backend. The caller must close both the returned conn and pool
// (conn first).
func (d *Differ) rootConn(ctx context.Context) (*sql.DB, *sql.Conn, error) {
	db, err := sql.Open("pgx", d.shadowConnStr)
	if err != nil {
		return nil, nil, fmt.Errorf("open shadow root connection: %w", err)
	}
	conn, err := db.Conn(ctx)
	if err != nil {
		_ = db.Close()
		return nil, nil, fmt.Errorf("acquire shadow root connection: %w", err)
	}
	// Don't let our own cleanup get killed by a role-level statement_timeout.
	if _, err := conn.ExecContext(ctx, "SET statement_timeout = 0"); err != nil {
		_ = conn.Close()
		_ = db.Close()
		return nil, nil, fmt.Errorf("disabling statement_timeout: %w", err)
	}
	return db, conn, nil
}

// databaseName reports which database a connection string resolves to, using the
// parser pgx itself uses so libpq environment fallbacks resolve identically.
func databaseName(connStr string) (string, error) {
	cfg, err := pgconn.ParseConfig(connStr)
	if err != nil {
		return "", err
	}
	if cfg.Database == "" {
		return "", fmt.Errorf("connection string names no database")
	}
	return cfg.Database, nil
}

// Close cleans up the temp database factory.
func (d *Differ) Close() error {
	return d.tempFactory.Close()
}

// Diff compares the desired DDL (from an S__ file) against the live database
// for a given schema and returns the ALTER statements needed to converge.
//
// When strict is false (default), only statements targeting objects defined in
// the DDL are included — undeclared objects in the live DB are ignored.
// When strict is true, all diff statements are included, including DROPs for
// objects that exist in the DB but not in the DDL.
func (d *Differ) Diff(ctx context.Context, liveDB *sql.DB, targetSchema string, desiredDDL []string, strict bool) (*DiffResult, error) {
	// Scope introspection to the schema this diff is about. Without this,
	// pg-schema-diff reads EVERY schema in the target database and diffs the
	// whole thing against a desired state that only ever describes one schema.
	// Two consequences, both severe on a real database:
	//
	//   - Cost: introspection walks every relation in the cluster. On a database
	//     carrying CDC-replicated schemas and TimescaleDB chunks that is tens of
	//     thousands of relations per diff, per schema folder — enough to make
	//     `plan` appear to hang.
	//   - Correctness: every object outside this schema reads as "not declared".
	//     Non-strict mode only hides that after the fact, by dropping statements
	//     that don't target a declared object; --strict has no such filter and
	//     would emit DROPs across unrelated schemas.
	opts := []diff.PlanOpt{
		diff.WithTempDbFactory(d.tempFactory),
		diff.WithIncludeSchemas(targetSchema),
	}

	var validationSkipped string
	var seededSchemas []string
	var recoveryNote string
	plan, err := diff.Generate(ctx,
		diff.DBSchemaSource(liveDB),
		diff.DDLSchemaSource(desiredDDL),
		opts...,
	)
	if err != nil {
		// Plan validation rebuilds the *current* schema in a throwaway database
		// and replays the generated statements against it. Scoping the diff to
		// one schema — which is what makes it correct and affordable — means
		// that rebuild sees only that schema, so it fails on any object whose
		// definition reaches outside it: a view over another schema's tables, a
		// materialized view over a view. That is a limitation of the validation
		// step, not a problem with the diff, and refusing to plan because of it
		// would make m8 unusable on any database whose views cross schemas.
		//
		// ONLY that phase degrades — see isValidationFailure. "The generated
		// DDL does not execute" and "the plan does not converge" still abort.
		if !isValidationFailure(err) {
			return nil, fmt.Errorf("failed to generate schema diff: %w", err)
		}
		validationSkipped = err.Error()

		// The rebuild failed because this schema holds an object defined in
		// terms of another one. Import those schemas into the throwaway
		// database and try the validation again -- a plan that can be checked
		// is worth an extra round trip, and until this existed the FIRST real
		// change to such a schema was refused outright by
		// --fail-on-unvalidated with no way forward but turning the check off.
		if seeded, retryPlan, rerr := d.validateWithDependencies(ctx, liveDB, targetSchema, desiredDDL, opts); rerr == nil && retryPlan != nil {
			plan = *retryPlan
			validationSkipped = ""
			seededSchemas = seeded
			if skipped := d.takeSkipped(); len(skipped) > 0 {
				recoveryNote = fmt.Sprintf(
					"imported %s into the rebuild; %d object(s) in it could not be created and were skipped (first: %s)",
					strings.Join(seeded, ", "), len(skipped), skipped[0])
			}
		} else {
			// Seeding is best effort by construction: it can turn a refused
			// plan into a validated one, never the reverse. Anything that goes
			// wrong here leaves the original degradation exactly as it was.
			if rerr != nil {
				recoveryNote = "importing the schemas it depends on did not help: " + firstLineOf(rerr.Error())
			}
			d.takeSkipped()
			// Regenerating means a second introspection of the target and a
			// second temp database. pg-schema-diff v1.0.5 offers no way to
			// avoid it: the plan it computed is discarded with the error, and
			// SchemaSource's only method takes an unexported dependency struct,
			// so an already-parsed schema cannot be handed back in. Reaching
			// this path at all is reported to the operator
			// (PLAN_NOT_VALIDATED), which is the signal to give the run a real
			// shadow instance.
			plan, err = diff.Generate(ctx,
				diff.DBSchemaSource(liveDB),
				diff.DDLSchemaSource(desiredDDL),
				append(opts, diff.WithDoNotValidatePlan())...,
			)
			if err != nil {
				return nil, fmt.Errorf("failed to generate schema diff (validation already skipped): %w", err)
			}
		}
	}

	// In default (non-strict) mode, only include statements targeting objects
	// defined in the DDL. In strict mode, include everything except _m8 internals.
	var definedObjects map[string]bool
	var undeclaredClasses []*regexp.Regexp
	if !strict {
		definedObjects = extractDefinedObjects(desiredDDL)
		undeclaredClasses = undeclaredAttachedClasses(desiredDDL)
		// A sequence behind a SERIAL or IDENTITY column is never named in the
		// DDL that declares it — the column says BIGSERIAL and Postgres derives
		// "<table>_<column>_seq" — so the desired state alone cannot say which
		// sequences are ours. The catalog can: pg_depend records the column each
		// sequence hangs off. Adopt every sequence whose owning table is
		// declared, and nothing else. Guessing by name prefix instead would
		// adopt an undeclared "probe_history" the moment "probe" is declared,
		// and then happily DROP its sequence.
		owned, err := ownedSequences(ctx, liveDB, targetSchema)
		if err != nil {
			return nil, err
		}
		for sequence, table := range owned {
			if definedObjects[table] {
				definedObjects[sequence] = true
			}
		}
	}

	result := &DiffResult{}

	for _, stmt := range plan.Statements {
		// Always exclude m8 internal schema
		lower := strings.ToLower(stmt.DDL)
		if strings.Contains(lower, `"_m8"`) || strings.Contains(lower, `_m8.`) {
			continue
		}

		// CREATE SCHEMA is m8's, not the diff's. A schema/{pg_schema}/ folder
		// implies its schema, and the engine creates it (Apply) or reports it
		// as pending (Plan) before the diff runs — so a CREATE SCHEMA here is
		// either a duplicate of that report or, if the ordering ever changed, a
		// second CREATE against a schema that already exists (42P06).
		if createSchemaRe.MatchString(stmt.DDL) {
			continue
		}

		if !strict {
			// An object attached to a declared table -- a trigger, a policy, the
			// RLS flag, replica identity -- is not "unrelated" to the name test:
			// the statement that removes it names the table, so the name test
			// keeps it. Whether it is ours to remove is decided by class, above.
			if matchesAny(undeclaredClasses, stmt.DDL) {
				continue
			}
			if !statementTargetsDefinedObject(stmt.DDL, definedObjects) {
				continue
			}
		}
		ds := DiffStatement{
			DDL:         stmt.DDL,
			Timeout:     stmt.Timeout,
			LockTimeout: stmt.LockTimeout,
		}
		for _, h := range stmt.Hazards {
			ds.Hazards = append(ds.Hazards, string(h.Type))
		}
		result.Statements = append(result.Statements, ds)
	}

	result.HasChanges = len(result.Statements) > 0
	result.SeededSchemas = seededSchemas
	result.RecoveryNote = recoveryNote
	if validationSkipped != "" {
		result.ValidationSkipped = true
		result.ValidationSkippedReason = validationSkipped
	}
	return result, nil
}

// validateWithDependencies retries plan validation with the schemas this one
// reaches into imported into the throwaway rebuild.
//
// Returns the schemas it imported and a validated plan, or a nil plan if the
// retry was not attempted or did not succeed. The error is advisory: it explains
// why the recovery failed, and never replaces the original degradation.
func (d *Differ) validateWithDependencies(
	ctx context.Context,
	liveDB *sql.DB,
	targetSchema string,
	desiredDDL []string,
	opts []diff.PlanOpt,
) ([]string, *diff.Plan, error) {
	deps, err := dependencySchemas(ctx, liveDB, targetSchema)
	if err != nil {
		return nil, nil, err
	}
	if len(deps) == 0 {
		// The rebuild failed for some other reason -- a self-referential object
		// m8 cannot help with. Nothing to import.
		return nil, nil, nil
	}

	n, err := countRelations(ctx, liveDB, deps)
	if err != nil {
		return nil, nil, err
	}
	if n > maxSeededRelations {
		return nil, nil, fmt.Errorf(
			"schemas %s hold %d relations, over the %d m8 will import into a validation rebuild",
			strings.Join(deps, ", "), n, maxSeededRelations)
	}

	seedDDL, err := d.harvestSchemaDDL(ctx, liveDB, deps)
	if err != nil {
		return nil, nil, err
	}
	if len(seedDDL) == 0 {
		return nil, nil, fmt.Errorf("schemas %s produced no DDL to import", strings.Join(deps, ", "))
	}

	disarm := d.seedTempDatabases(seedDDL)
	defer disarm()

	plan, err := diff.Generate(ctx,
		diff.DBSchemaSource(liveDB),
		diff.DDLSchemaSource(desiredDDL),
		opts...,
	)
	if err != nil {
		return nil, nil, err
	}
	return deps, &plan, nil
}

// Phase strings pg-schema-diff v1.0.5 puts on the errors its plan-validation
// step returns. assertValidPlan runs four phases inside one wrap:
//
//	validating migration plan: inserting schema in temporary database: …
//	validating migration plan: running migration plan: …
//	validating migration plan: fetching schema from migrated database: …
//	validating migration plan: validating plan failed. diff detected: …
//
// Only the first is a limitation of how m8 scopes the diff. The other three are
// the entire safety value of validation — "the generated DDL does not execute"
// and "the plan does not converge" — and must stay fatal.
const (
	validationWrap     = "validating migration plan: "
	shadowRebuildPhase = "inserting schema in temporary database: "
)

// isValidationFailure reports whether an error is the ONE plan-validation
// failure m8 is allowed to degrade past: pg-schema-diff could not rebuild the
// current schema in a throwaway database. Scoping the diff to a single schema —
// which is what makes it correct and affordable — means that rebuild sees only
// that schema, so it fails on any object whose definition reaches outside it.
// Refusing to plan because of that would make m8 unusable on any database whose
// views cross schemas.
//
// Every other validation phase still aborts. In particular "running migration
// plan" means the generated DDL does not execute, which against a production
// primary is the difference between a refusal and a migration that dies
// halfway.
//
// The match is a prefix on the wrap and on the phase pg-schema-diff nests
// inside it, never strings.Contains: the outer error appends
// pretty.Formatter(plan), i.e. every DDL statement in the plan, so a Contains
// test can be satisfied by DDL text rather than by the phase that actually
// failed.
func isValidationFailure(err error) bool {
	if err == nil {
		return false
	}
	if !strings.HasPrefix(err.Error(), validationWrap) {
		return false
	}
	inner := errors.Unwrap(err)
	return inner != nil && strings.HasPrefix(inner.Error(), shadowRebuildPhase)
}

var (
	// Matches: CREATE TABLE [IF NOT EXISTS] [schema.]tablename
	createTableRe = regexp.MustCompile(`(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:"?\w+"?\.)?("?\w+"?)`)
	// Matches: CREATE [UNIQUE] INDEX [CONCURRENTLY] [IF NOT EXISTS] indexname
	createIndexRe = regexp.MustCompile(`(?i)CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?("?\w+"?)`)
)

// extractDefinedObjects parses the desired DDL statements and returns the set
// of object names (tables, indexes) that are explicitly defined. Names are
// stored unquoted and lowercased for case-insensitive matching.
func extractDefinedObjects(ddlStatements []string) map[string]bool {
	objects := make(map[string]bool)
	combined := strings.Join(ddlStatements, "\n")

	for _, m := range createTableRe.FindAllStringSubmatch(combined, -1) {
		name := strings.Trim(m[1], `"`)
		objects[strings.ToLower(name)] = true
	}
	for _, m := range createIndexRe.FindAllStringSubmatch(combined, -1) {
		name := strings.Trim(m[1], `"`)
		objects[strings.ToLower(name)] = true
	}
	return objects
}

var (
	// createStatementRe matches a statement that brings a new object into
	// existence. Anchored: only the leading keyword counts, never CREATE
	// appearing inside a body or a string literal.
	createStatementRe = regexp.MustCompile(`(?is)^\s*CREATE\s`)
	// createSchemaRe matches the schema creation m8 does for itself.
	createSchemaRe = regexp.MustCompile(`(?is)^\s*CREATE\s+SCHEMA\s`)
)

// statementTargetsDefinedObject returns true if the DDL statement modifies an
// object that was defined in the S__ file. This prevents pg-schema-diff from
// generating DROP/ALTER/REVOKE statements for unrelated objects that exist in
// the live database but aren't mentioned in the desired DDL.
func statementTargetsDefinedObject(ddl string, defined map[string]bool) bool {
	lower := strings.ToLower(ddl)

	// Always exclude m8 internal schema
	if strings.Contains(lower, `"_m8"`) || strings.Contains(lower, `_m8.`) {
		return false
	}

	// Exclude GRANT/REVOKE — privileges are managed by R__ migrations, not S__
	if strings.HasPrefix(lower, "grant ") || strings.HasPrefix(lower, "revoke ") {
		return false
	}

	// A CREATE is always ours. pg-schema-diff emits CREATE only for objects
	// present in the desired schema and absent from the (schema-scoped) current
	// one, so a CREATE can never reach an undeclared live object — which is the
	// only thing this filter exists to protect.
	//
	// It is also the only way some declared objects are reachable at all. The
	// sequence behind a SERIAL column arrives as
	//
	//	CREATE SEQUENCE "public"."probe_id_seq"
	//
	// which contains neither `"probe"` nor a word-bounded `probe` ('_' is an
	// identifier character), so the name test below drops it — while the
	// matching ALTER SEQUENCE … OWNED BY "public"."probe"."id" survives, because
	// that one does mention the table. m8 used to paper over the asymmetry by
	// synthesizing its own CREATE SEQUENCE from a regex over the generated DDL;
	// that fixup was anchored on CREATE TABLE, so ALTER TABLE … ADD COLUMN …
	// BIGSERIAL got none and died on apply with 42P01.
	if createStatementRe.MatchString(ddl) {
		return true
	}

	// Check if any defined object name appears in the statement.
	// pg-schema-diff quotes table names ("users") but not index names (idx_foo).
	for name := range defined {
		if strings.Contains(lower, `"`+name+`"`) {
			return true
		}
		if containsWord(lower, name) {
			return true
		}
	}
	return false
}

// attachedClasses are object classes that hang off a table rather than standing
// on their own. pg-schema-diff introspects every one of them; `m8 dump` captures
// none of them; so on a database bootstrapped by `m8 dump` the desired state
// never mentions them and the diff proposes removing them -- and because the
// statement that removes one NAMES THE TABLE it hangs off, the declared-object
// test keeps it. A dumped baseline therefore planned, and applied:
//
//	DROP TRIGGER "t_audit_trg" ON "public"."t"
//	DROP POLICY "t_tenant_isolation" ON "public"."t"
//	ALTER TABLE "public"."t" DISABLE ROW LEVEL SECURITY
//	ALTER TABLE "public"."t" REPLICA IDENTITY DEFAULT
//
// against a database whose migration files never mentioned any of them. The plan
// validates cleanly, so --fail-on-unvalidated is no protection either.
//
// Non-strict mode's contract is that objects the migration files do not declare
// are left alone, so the test is per CLASS: if nothing in this schema folder
// declares a trigger, no statement may remove one. A folder that DOES declare
// triggers gets the old behaviour, because then an undeclared trigger really is
// one the desired state says should not exist. --strict is unaffected: it means
// "these files are the whole truth", and removing what they omit is the point.
var attachedClasses = []struct {
	name      string
	declared  *regexp.Regexp // the class appears in the desired DDL
	statement *regexp.Regexp // a generated statement acts on the class
}{
	{
		name:      "trigger",
		declared:  regexp.MustCompile(`(?is)\bCREATE\s+(?:OR\s+REPLACE\s+)?(?:CONSTRAINT\s+)?TRIGGER\b`),
		statement: regexp.MustCompile(`(?is)^\s*(?:CREATE|ALTER|DROP)\s+(?:OR\s+REPLACE\s+)?(?:CONSTRAINT\s+)?TRIGGER\b`),
	},
	{
		name:      "policy",
		declared:  regexp.MustCompile(`(?is)\bCREATE\s+POLICY\b`),
		statement: regexp.MustCompile(`(?is)^\s*(?:CREATE|ALTER|DROP)\s+POLICY\b`),
	},
	{
		name:      "row level security",
		declared:  regexp.MustCompile(`(?is)\bROW\s+LEVEL\s+SECURITY\b`),
		statement: regexp.MustCompile(`(?is)\bROW\s+LEVEL\s+SECURITY\b`),
	},
	{
		name:      "replica identity",
		declared:  regexp.MustCompile(`(?is)\bREPLICA\s+IDENTITY\b`),
		statement: regexp.MustCompile(`(?is)\bREPLICA\s+IDENTITY\b`),
	},
}

// undeclaredAttachedClasses returns the statement patterns for every attached
// class this desired state says nothing about.
func undeclaredAttachedClasses(desiredDDL []string) []*regexp.Regexp {
	combined := strings.Join(desiredDDL, "\n")
	var out []*regexp.Regexp
	for _, c := range attachedClasses {
		if !c.declared.MatchString(combined) {
			out = append(out, c.statement)
		}
	}
	return out
}

func matchesAny(patterns []*regexp.Regexp, s string) bool {
	for _, re := range patterns {
		if re.MatchString(s) {
			return true
		}
	}
	return false
}

// ownedSequences returns the sequences in targetSchema that belong to a column,
// mapped to the (lowercased) name of the table that owns them. These are the
// sequences SERIAL and GENERATED … AS IDENTITY create: they carry an automatic
// (deptype 'a') or internal (deptype 'i') dependency on the owning column, which
// is what makes them droppable with the table.
//
// Without this, a declared table that stops being SERIAL leaves its sequence
// behind forever: the plan's DROP SEQUENCE "public"."probe_id_seq" names no
// declared object and is filtered away, so every run re-proposes nothing and the
// orphan is never reclaimed.
func ownedSequences(ctx context.Context, liveDB *sql.DB, targetSchema string) (map[string]string, error) {
	rows, err := liveDB.QueryContext(ctx, `
		SELECT lower(s.relname), lower(t.relname)
		FROM pg_class s
		JOIN pg_namespace n ON n.oid = s.relnamespace
		JOIN pg_depend d
		  ON d.classid = 'pg_class'::regclass
		 AND d.objid = s.oid
		 AND d.refclassid = 'pg_class'::regclass
		 AND d.deptype IN ('a', 'i')
		JOIN pg_class t ON t.oid = d.refobjid
		-- Same schema on both sides: definedObjects holds bare table names, so a
		-- sequence owned by a same-named table in ANOTHER schema would otherwise
		-- be adopted on the strength of the name alone.
		 AND t.relnamespace = n.oid
		WHERE s.relkind = 'S'
		  AND n.nspname = $1`, targetSchema)
	if err != nil {
		return nil, fmt.Errorf("listing owned sequences in %s: %w", targetSchema, err)
	}
	defer func() { _ = rows.Close() }()

	owned := make(map[string]string)
	for rows.Next() {
		var sequence, table string
		if err := rows.Scan(&sequence, &table); err != nil {
			return nil, fmt.Errorf("scanning owned sequence in %s: %w", targetSchema, err)
		}
		owned[sequence] = table
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating owned sequences in %s: %w", targetSchema, err)
	}
	return owned, nil
}

// containsWord checks if s contains word as a whole word (not a substring of
// a longer identifier). Uses simple boundary checking on adjacent characters.
func containsWord(s, word string) bool {
	for i := 0; i <= len(s)-len(word); i++ {
		if s[i:i+len(word)] != word {
			continue
		}
		// Check character before
		if i > 0 && isIdentChar(s[i-1]) {
			continue
		}
		// Check character after
		end := i + len(word)
		if end < len(s) && isIdentChar(s[end]) {
			continue
		}
		return true
	}
	return false
}

func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
		(c >= '0' && c <= '9') || c == '_'
}

// appendConnOption appends a PostgreSQL connection option to a connection string.
// For URL format, appends as a query parameter. For key-value format, appends as options.
func appendConnOption(connStr, key, value string) string {
	if strings.HasPrefix(connStr, "postgres://") || strings.HasPrefix(connStr, "postgresql://") {
		sep := "?"
		if strings.Contains(connStr, "?") {
			sep = "&"
		}
		return connStr + sep + "options=-c+" + key + "%3D" + value
	}
	// Key-value format: append options parameter
	if strings.Contains(connStr, "options=") {
		return strings.Replace(connStr, "options='", "options='-c "+key+"="+value+" ", 1)
	}
	return connStr + " options='-c " + key + "=" + value + "'"
}

// replaceDBName replaces the database name in a PostgreSQL connection string.
// Handles both URL format (postgres://.../<dbname>) and key=value format (dbname=...).
func replaceDBName(connStr, newDB string) string {
	// URL format: postgres://user:pass@host:port/dbname?params
	if strings.HasPrefix(connStr, "postgres://") || strings.HasPrefix(connStr, "postgresql://") {
		// Find the path component (database name)
		parts := strings.SplitN(connStr, "?", 2)
		base := parts[0]

		// Find the last / which precedes the dbname
		lastSlash := strings.LastIndex(base, "/")
		if lastSlash == -1 {
			return connStr
		}

		newBase := base[:lastSlash+1] + newDB
		if len(parts) > 1 {
			return newBase + "?" + parts[1]
		}
		return newBase
	}

	// Key=value format: host=... port=... dbname=... user=...
	parts := strings.Fields(connStr)
	var result []string
	found := false
	for _, part := range parts {
		if strings.HasPrefix(part, "dbname=") {
			result = append(result, "dbname="+newDB)
			found = true
		} else {
			result = append(result, part)
		}
	}
	if !found {
		result = append(result, "dbname="+newDB)
	}
	return strings.Join(result, " ")
}
