package schema

import (
	"context"
	"database/sql"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/stripe/pg-schema-diff/pkg/diff"
	"github.com/stripe/pg-schema-diff/pkg/tempdb"
)

// DiffResult holds the output of diffing a schema file against the live database.
type DiffResult struct {
	Name       string          // from S__{name}.sql
	Statements []DiffStatement // ordered ALTER statements to reach desired state
	HasChanges bool
}

// DiffStatement represents a single DDL statement generated by the schema differ.
type DiffStatement struct {
	DDL         string        // The SQL statement to execute.
	Hazards     []string      // Safety warnings (e.g., "ACQUIRES_ACCESS_EXCLUSIVE_LOCK").
	Timeout     time.Duration // Suggested statement_timeout.
	LockTimeout time.Duration // Suggested lock_timeout.
}

// tempDropTimeout caps how long pg-schema-diff's cleanup may spend dropping a
// temporary shadow database. The library defaults to 3s (tempdb.DefaultStatementTimeout),
// which is far too aggressive on a loaded instance: a DROP DATABASE that exceeds it
// is interrupted, leaving the database INVALID (pg_database.datconnlimit = -2) and
// orphaned. A generous ceiling lets the drop complete. See SweepInvalidTempDBs for
// remediation of any that still slip through.
const tempDropTimeout = 5 * time.Minute

// Differ computes the difference between a desired-state DDL definition
// and the live database schema, producing ALTER statements to converge.
type Differ struct {
	connStr       string         // connection string for the live target database
	shadowConnStr string         // connection string for the instance hosting temp DBs
	tempFactory   tempdb.Factory // creates temp DBs for DDL parsing/plan validation
}

// NewDiffer creates a Differ. The live target database (introspected for the
// current schema) is reached via targetConnStr. Temporary shadow databases —
// which pg-schema-diff creates and drops to parse desired DDL and validate plans
// (named pgschemadiff_tmp_*) — are created on the instance reached via
// shadowConnStr.
//
// IMPORTANT: when shadowConnStr is empty, temp databases are created on the
// TARGET instance itself. Against a production primary this churns
// CREATE/DROP DATABASE on the live cluster — pass a separate, non-production
// shadow instance to avoid that.
func NewDiffer(ctx context.Context, targetConnStr, shadowConnStr string) (*Differ, error) {
	if shadowConnStr == "" {
		shadowConnStr = targetConnStr
	}

	factory, err := tempdb.NewOnInstanceFactory(ctx, func(ctx context.Context, dbName string) (*sql.DB, error) {
		// Replace the database name first, THEN append statement_timeout=0.
		// replaceDBName tokenizes key=value DSNs on whitespace and would corrupt
		// a quoted options='...' value, so options must be appended last.
		// statement_timeout=0 must live in the connection string itself because
		// sql.Open is lazy and a SET may not reach the factory's connections.
		tempConnStr := appendConnOption(replaceDBName(shadowConnStr, dbName), "statement_timeout", "0")
		return sql.Open("pgx", tempConnStr)
	}, tempdb.WithDropTimeout(tempDropTimeout))
	if err != nil {
		return nil, fmt.Errorf("failed to create temp database factory: %w", err)
	}

	return &Differ{
		connStr:       targetConnStr,
		shadowConnStr: shadowConnStr,
		tempFactory:   factory,
	}, nil
}

// SweepInvalidTempDBs drops any orphaned pgschemadiff_tmp_* databases on the
// shadow instance that Postgres has marked INVALID (datconnlimit = -2) — the
// residue of a DROP DATABASE that was interrupted (e.g. by a statement timeout).
// Invalid databases cannot be connected to, so dropping them is always safe even
// when another m8 process is running. It returns the number of databases dropped.
func (d *Differ) SweepInvalidTempDBs(ctx context.Context) (int, error) {
	db, conn, err := d.rootConn(ctx)
	if err != nil {
		return 0, err
	}
	defer db.Close()
	defer conn.Close()

	rows, err := conn.QueryContext(ctx,
		`SELECT datname FROM pg_database WHERE datname LIKE 'pgschemadiff\_tmp\_%' AND datconnlimit = -2`)
	if err != nil {
		return 0, fmt.Errorf("listing invalid temp databases: %w", err)
	}
	var names []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			rows.Close()
			return 0, fmt.Errorf("scanning temp database name: %w", err)
		}
		names = append(names, n)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return 0, fmt.Errorf("iterating temp databases: %w", err)
	}

	dropped := 0
	for _, n := range names {
		stmt := fmt.Sprintf("DROP DATABASE IF EXISTS %s WITH (FORCE)", quoteIdent(n))
		if _, err := conn.ExecContext(ctx, stmt); err != nil {
			return dropped, fmt.Errorf("dropping orphaned temp database %s: %w", n, err)
		}
		dropped++
	}
	return dropped, nil
}

// rootConn opens a single pinned connection to the shadow instance's root
// ("postgres") database with statement_timeout disabled. Pinning one connection
// (rather than using the *sql.DB pool directly) guarantees the statement_timeout
// reset and the subsequent statements all run on the same backend. The caller
// must close both the returned conn and pool (conn first).
func (d *Differ) rootConn(ctx context.Context) (*sql.DB, *sql.Conn, error) {
	rootStr := replaceDBName(d.shadowConnStr, "postgres")
	db, err := sql.Open("pgx", rootStr)
	if err != nil {
		return nil, nil, fmt.Errorf("open shadow root connection: %w", err)
	}
	conn, err := db.Conn(ctx)
	if err != nil {
		db.Close()
		return nil, nil, fmt.Errorf("acquire shadow root connection: %w", err)
	}
	// Don't let our own cleanup get killed by a role-level statement_timeout.
	if _, err := conn.ExecContext(ctx, "SET statement_timeout = 0"); err != nil {
		conn.Close()
		db.Close()
		return nil, nil, fmt.Errorf("disabling statement_timeout: %w", err)
	}
	return db, conn, nil
}

// quoteIdent double-quotes a PostgreSQL identifier, escaping embedded quotes.
func quoteIdent(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}

// Close cleans up the temp database factory.
func (d *Differ) Close() error {
	return d.tempFactory.Close()
}

// Diff compares the desired DDL (from an S__ file) against the live database
// for a given schema and returns the ALTER statements needed to converge.
//
// When strict is false (default), only statements targeting objects defined in
// the DDL are included — undeclared objects in the live DB are ignored.
// When strict is true, all diff statements are included, including DROPs for
// objects that exist in the DB but not in the DDL.
func (d *Differ) Diff(ctx context.Context, liveDB *sql.DB, targetSchema string, desiredDDL []string, strict bool) (*DiffResult, error) {
	plan, err := diff.Generate(ctx,
		diff.DBSchemaSource(liveDB),
		diff.DDLSchemaSource(desiredDDL),
		diff.WithTempDbFactory(d.tempFactory),
	)
	if err != nil {
		return nil, fmt.Errorf("failed to generate schema diff: %w", err)
	}

	// In default (non-strict) mode, only include statements targeting objects
	// defined in the DDL. In strict mode, include everything except _m8 internals.
	var definedObjects map[string]bool
	if !strict {
		definedObjects = extractDefinedObjects(desiredDDL)
	}

	result := &DiffResult{}

	for _, stmt := range plan.Statements {
		// Always exclude m8 internal schema
		lower := strings.ToLower(stmt.DDL)
		if strings.Contains(lower, `"_m8"`) || strings.Contains(lower, `_m8.`) {
			continue
		}

		if !strict {
			if !statementTargetsDefinedObject(stmt.DDL, definedObjects) {
				continue
			}
		}
		ds := DiffStatement{
			DDL:         stmt.DDL,
			Timeout:     stmt.Timeout,
			LockTimeout: stmt.LockTimeout,
		}
		for _, h := range stmt.Hazards {
			ds.Hazards = append(ds.Hazards, string(h.Type))
		}
		result.Statements = append(result.Statements, ds)
	}

	result.HasChanges = len(result.Statements) > 0
	return result, nil
}

var (
	// Matches: CREATE TABLE [IF NOT EXISTS] [schema.]tablename
	createTableRe = regexp.MustCompile(`(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:"?\w+"?\.)?("?\w+"?)`)
	// Matches: CREATE [UNIQUE] INDEX [CONCURRENTLY] [IF NOT EXISTS] indexname
	createIndexRe = regexp.MustCompile(`(?i)CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?("?\w+"?)`)
)

// extractDefinedObjects parses the desired DDL statements and returns the set
// of object names (tables, indexes) that are explicitly defined. Names are
// stored unquoted and lowercased for case-insensitive matching.
func extractDefinedObjects(ddlStatements []string) map[string]bool {
	objects := make(map[string]bool)
	combined := strings.Join(ddlStatements, "\n")

	for _, m := range createTableRe.FindAllStringSubmatch(combined, -1) {
		name := strings.Trim(m[1], `"`)
		objects[strings.ToLower(name)] = true
	}
	for _, m := range createIndexRe.FindAllStringSubmatch(combined, -1) {
		name := strings.Trim(m[1], `"`)
		objects[strings.ToLower(name)] = true
	}
	return objects
}

// statementTargetsDefinedObject returns true if the DDL statement modifies an
// object that was defined in the S__ file. This prevents pg-schema-diff from
// generating DROP/ALTER/REVOKE statements for unrelated objects that exist in
// the live database but aren't mentioned in the desired DDL.
func statementTargetsDefinedObject(ddl string, defined map[string]bool) bool {
	lower := strings.ToLower(ddl)

	// Always exclude m8 internal schema
	if strings.Contains(lower, `"_m8"`) || strings.Contains(lower, `_m8.`) {
		return false
	}

	// Exclude GRANT/REVOKE — privileges are managed by R__ migrations, not S__
	if strings.HasPrefix(lower, "grant ") || strings.HasPrefix(lower, "revoke ") {
		return false
	}

	// Check if any defined object name appears in the statement.
	// pg-schema-diff quotes table names ("users") but not index names (idx_foo).
	for name := range defined {
		if strings.Contains(lower, `"`+name+`"`) {
			return true
		}
		if containsWord(lower, name) {
			return true
		}
	}
	return false
}

// containsWord checks if s contains word as a whole word (not a substring of
// a longer identifier). Uses simple boundary checking on adjacent characters.
func containsWord(s, word string) bool {
	for i := 0; i <= len(s)-len(word); i++ {
		if s[i:i+len(word)] != word {
			continue
		}
		// Check character before
		if i > 0 && isIdentChar(s[i-1]) {
			continue
		}
		// Check character after
		end := i + len(word)
		if end < len(s) && isIdentChar(s[end]) {
			continue
		}
		return true
	}
	return false
}

func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
		(c >= '0' && c <= '9') || c == '_'
}

// appendConnOption appends a PostgreSQL connection option to a connection string.
// For URL format, appends as a query parameter. For key-value format, appends as options.
func appendConnOption(connStr, key, value string) string {
	if strings.HasPrefix(connStr, "postgres://") || strings.HasPrefix(connStr, "postgresql://") {
		sep := "?"
		if strings.Contains(connStr, "?") {
			sep = "&"
		}
		return connStr + sep + "options=-c+" + key + "%3D" + value
	}
	// Key-value format: append options parameter
	if strings.Contains(connStr, "options=") {
		return strings.Replace(connStr, "options='", "options='-c "+key+"="+value+" ", 1)
	}
	return connStr + " options='-c " + key + "=" + value + "'"
}

// replaceDBName replaces the database name in a PostgreSQL connection string.
// Handles both URL format (postgres://.../<dbname>) and key=value format (dbname=...).
func replaceDBName(connStr, newDB string) string {
	// URL format: postgres://user:pass@host:port/dbname?params
	if strings.HasPrefix(connStr, "postgres://") || strings.HasPrefix(connStr, "postgresql://") {
		// Find the path component (database name)
		parts := strings.SplitN(connStr, "?", 2)
		base := parts[0]

		// Find the last / which precedes the dbname
		lastSlash := strings.LastIndex(base, "/")
		if lastSlash == -1 {
			return connStr
		}

		newBase := base[:lastSlash+1] + newDB
		if len(parts) > 1 {
			return newBase + "?" + parts[1]
		}
		return newBase
	}

	// Key=value format: host=... port=... dbname=... user=...
	parts := strings.Fields(connStr)
	var result []string
	found := false
	for _, part := range parts {
		if strings.HasPrefix(part, "dbname=") {
			result = append(result, "dbname="+newDB)
			found = true
		} else {
			result = append(result, part)
		}
	}
	if !found {
		result = append(result, "dbname="+newDB)
	}
	return strings.Join(result, " ")
}
